# Site settings
title: GG-Sec - IT Security Consulting
email: contact@gg-sec.com
url: https://example.github.io
description: "GG-Sec is specialized in providing IT security consulting services with the goal to uncover real world vulnerabilities in your systems and applications"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: GG-Sec

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/c4tch4ll
  - title: linkedin
    url: https://www.linkedin.com/in/johannes-baer-34628386/


# Build settings
markdown: kramdown
permalink: pretty
